export default {
    "form": [
        {
            "name": "工单标题",
            "code": "title",
            "type": "singleRowText",
            "default_value": null,
            "type_desc": "单行文本",
            "validation": "none",
            "min_length": null,
            "max_length": 40,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                }
            ],
            "is_required": 1,
            "builtin": 1,
            "cascade": null,
            "id": "92e430a6c44546c9a245d1295cc58b85",
            "defaultValue": null,
            "maxLength": 40,
            "minLength": null,
            "isRequired": 1,
            "typeDesc": "单行文本",
            "formatDate": null
        },
        {
            "name": "优先级",
            "code": "urgentLevel",
            "type": "singleSel",
            "default_value": null,
            "type_desc": "单选",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "极低",
                    "value": 1,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "低",
                    "value": 2,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "中",
                    "value": 3,
                    "select": 1,
                    "color": "#ef5350"
                },
                {
                    "label": "高",
                    "value": 4,
                    "select": 0,
                    "color": "#9ccc65"
                },
                {
                    "label": "极高",
                    "value": 5,
                    "select": 0,
                    "color": "#ffa726"
                }
            ],
            "is_required": 1,
            "builtin": 1,
            "cascade": null,
            "id": "709117c0be68454fa358f98ae2950cbd",
            "defaultValue": null,
            "maxLength": null,
            "minLength": null,
            "isRequired": 1,
            "typeDesc": "单选",
            "formatDate": null
        },
        {
            "name": "工单描述",
            "code": "ticketDesc",
            "type": "multiRowText",
            "default_value": null,
            "type_desc": "多行文本",
            "validation": null,
            "min_length": null,
            "max_length": 500,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                }
            ],
            "is_required": 0,
            "builtin": 1,
            "cascade": null,
            "id": "564caa84bc7a488f9e703a97dd3ee418",
            "defaultValue": null,
            "maxLength": 500,
            "minLength": null,
            "isRequired": 0,
            "typeDesc": "多行文本",
            "formatDate": null
        },
        {
            "name": "报告人",
            "code": "announcer",
            "type": "singleRowText",
            "default_value": null,
            "type_desc": "单行文本",
            "validation": "none",
            "min_length": null,
            "max_length": 20,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                }
            ],
            "is_required": 2,
            "builtin": 1,
            "cascade": null,
            "id": "319f022ff9aa484a9436d361a878ec0e",
            "defaultValue": "lalalalala",
            "maxLength": 20,
            "minLength": null,
            "isRequired": 2,
            "typeDesc": "单行文本",
            "formatDate": null
        },
        {
            "name": "上线时间",
            "code": "releaseTime",
            "type": "dateTime",
            "default_value": null,
            "type_desc": "日期时间",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                }
            ],
            "is_required": 0,
            "builtin": 1,
            "cascade": null,
            "id": "78c8dc6953854a60a1f1b2d6f0dc03a9",
            "defaultValue": null,
            "maxLength": null,
            "minLength": null,
            "isRequired": 0,
            "typeDesc": "日期时间",
            "formatDate": null
        },
        {
            "name": "上线结果",
            "code": "releaseResult",
            "type": "listSel",
            "default_value": null,
            "type_desc": "下拉菜单",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "成功",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "失败",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                }
            ],
            "is_required": 1,
            "builtin": 1,
            "cascade": null,
            "id": "79c030646cd64e82a5bce2d5102fe9ce",
            "defaultValue": null,
            "maxLength": null,
            "minLength": null,
            "isRequired": 1,
            "typeDesc": "下拉菜单",
            "formatDate": null
        },
        {
            "name": "满意度",
            "code": "score",
            "type": "singleSel",
            "default_value": null,
            "type_desc": "单选",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "非常满意",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "满意",
                    "value": 1,
                    "select": 1,
                    "color": "#66bb6a"
                },
                {
                    "label": "一般",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                },
                {
                    "label": "不满意",
                    "value": 3,
                    "select": 0,
                    "color": "#9ccc65"
                },
                {
                    "label": "非常不满意",
                    "value": 4,
                    "select": 0,
                    "color": "#ffa726"
                }
            ],
            "is_required": 1,
            "builtin": 1,
            "cascade": null,
            "id": "f2acda365e1345ccb63b1536b2c61b8f",
            "defaultValue": null,
            "maxLength": null,
            "minLength": null,
            "isRequired": 1,
            "typeDesc": "单选",
            "formatDate": null
        },
        {
            "name": "变更经理",
            "code": "chgManager",
            "type": "user",
            "default_value": null,
            "type_desc": "人员",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                }
            ],
            "is_required": 0,
            "builtin": 1,
            "cascade": null,
            "id": "740572f8d64f41949775a31ab02e2521",
            "defaultValue": null,
            "maxLength": null,
            "minLength": null,
            "isRequired": 0,
            "typeDesc": "人员",
            "formatDate": null
        },
        {
            "name": "解决方案",
            "code": "solvent",
            "type": "multiRowText",
            "default_value": null,
            "type_desc": "多行文本",
            "validation": null,
            "min_length": null,
            "max_length": 100,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": [
                {
                    "label": "",
                    "value": 0,
                    "select": 0,
                    "color": "#008ed2"
                },
                {
                    "label": "",
                    "value": 1,
                    "select": 0,
                    "color": "#66bb6a"
                },
                {
                    "label": "",
                    "value": 2,
                    "select": 0,
                    "color": "#ef5350"
                }
            ],
            "is_required": 0,
            "builtin": 1,
            "cascade": null,
            "id": "7ebbc2cb39cb40b8834d8473553c4068",
            "defaultValue": null,
            "maxLength": 100,
            "minLength": null,
            "isRequired": 0,
            "typeDesc": "多行文本",
            "formatDate": null
        },
        {
          "name": "ma多选",
          "code": "duo",
          "type": "multiSel",
          "default_value": "",
          "type_desc": "多选",
          "validation": null,
          "min_length": null,
          "max_length": null,
          "min": 0,
          "max": 0,
          "unit": null,
          "precision": null,
          "format_date": null,
          "params": [
              {
                  "label": "打得过",
                  "value": "dd",
                  "select": 1,
                  "color": "#008ed2"
              },
              {
                  "label": "水电费",
                  "value": "dsa",
                  "select": 1,
                  "color": "#ef5350"
              },
              {
                  "label": "大地飞歌",
                  "value": "dsf",
                  "select": 0,
                  "color": "#26a69a"
              }
          ],
          "is_required": 0,
          "builtin": 0,
          "cascade": null,
          "id": "9196b958347142b7a50eccd9639d4077",
          "defaultValue": "",
          "minLength": null,
          "maxLength": null,
          "typeDesc": "多选",
          "formatDate": null,
          "isRequired": 0
        },
        {
            "name": "test",
            "code": "test",
            "type": "double",
            "default_value": "0.25",
            "type_desc": "小数",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": "a",
            "precision": 2,
            "format_date": null,
            "params": null,
            "is_required": 0,
            "builtin": 0,
            "cascade": null,
            "id": "ca41e39940c34df58c011318cccd2cdb",
            "defaultValue": "0.25",
            "maxLength": null,
            "minLength": null,
            "isRequired": 0,
            "typeDesc": "小数",
            "formatDate": null
        },
        {
            "name": "级联",
            "code": "wer",
            "type": "cascader",
            "default_value": "",
            "type_desc": "级联",
            "validation": null,
            "min_length": null,
            "max_length": null,
            "min": 0,
            "max": 0,
            "unit": null,
            "precision": null,
            "format_date": null,
            "params": null,
            "is_required": 0,
            "builtin": 0,
            "cascade": [
                {
                    "value": 0,
                    "label": "ww",
                    "select": 0,
                    "color": "#008ed2",
                    "children": [
                        {
                            "value": 0,
                            "label": "ee",
                            "select": 0,
                            "color": null,
                            "children": [
                                {
                                    "value": 0,
                                    "label": "rr",
                                    "select": 0,
                                    "color": null,
                                    "children": null
                                }
                            ]
                        }
                    ]
                },
                {
                    "value": 3,
                    "label": "tt",
                    "select": 0,
                    "color": "#ef5350",
                    "children": [
                        {
                            "value": 0,
                            "label": "yy",
                            "select": 0,
                            "color": null,
                            "children": [
                                {
                                    "value": 0,
                                    "label": "uu",
                                    "select": 0,
                                    "color": null,
                                    "children": null
                                }
                            ]
                        }
                    ]
                }
            ],
            "id": "58ef23307b80477f95508fcfe83edf36",
            "defaultValue": "",
            "maxLength": null,
            "minLength": null,
            "isRequired": 0,
            "typeDesc": "级联",
            "formatDate": null
        }
    ],
    "activityVOs": [
        {
            "id": "bf7053ddb364402fb3ede0fceca66faf",
            "name": "一线处理",
            "policy": 2,
            "users": [
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm019",
                    "username": "itsm019",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm019@uyun.cn",
                    "mobile": "18000000220",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "025871a3e45345c88fd9bae4b78460e4",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm019",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968569
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm001",
                    "username": "itsm001",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm001@uyun.cn",
                    "mobile": "18000000202",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "03170d547ae14b4abf1cd1ce4b099713",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157967000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm001",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157967812
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm015",
                    "username": "itsm015",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm015@uyun.cn",
                    "mobile": "18000000216",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "06c4ac2d313a49499af8467967ae2681",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm015",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968344
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm010",
                    "username": "itsm010",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm010@uyun.cn",
                    "mobile": "18000000211",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "11057d1d7a5a4caf87925b58f47a396b",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm010",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968185
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm005",
                    "username": "itsm005",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm005@uyun.cn",
                    "mobile": "18000000206",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "1567b13112714c8b9e9d44688bb002d5",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm005",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968019
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm007",
                    "username": "itsm007",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm007@uyun.cn",
                    "mobile": "18000000208",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "22e0eb534d964bb3bf48f8dc74264087",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm007",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968082
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm011",
                    "username": "itsm011",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm011@uyun.cn",
                    "mobile": "18000000212",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "238d3d523ec34632adc6ecb3e3412dc7",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm011",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968218
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm016",
                    "username": "itsm016",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm016@uyun.cn",
                    "mobile": "18000000217",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "4d31b7b7dde54357a33104d28a954105",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm016",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968416
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm004",
                    "username": "itsm004",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm004@uyun.cn",
                    "mobile": "18000000205",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "5d0ab473a70d429a884b57ca4f892232",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157967000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm004",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157967979
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm018",
                    "username": "itsm018",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm018@uyun.cn",
                    "mobile": "18000000219",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "6349baa120bb48238dd1b9c38353be2d",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm018",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968536
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm008",
                    "username": "itsm008",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm008@uyun.cn",
                    "mobile": "18000000209",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "7b99f4b1944c40fdb8cc33e14d5746df",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm008",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968112
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm002",
                    "username": "itsm002",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm002@uyun.cn",
                    "mobile": "18000000203",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "a39733a2026d47f58476f9964607d860",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157967000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm002",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157967889
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm009",
                    "username": "itsm009",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm009@uyun.cn",
                    "mobile": "18000000210",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "a8d0718220f74b53b0dec6a5dcca1808",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm009",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968153
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm013",
                    "username": "itsm013",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm013@uyun.cn",
                    "mobile": "18000000214",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "b3c4d10a850f4bdeb45098613aade616",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm013",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968279
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm017",
                    "username": "itsm017",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm017@uyun.cn",
                    "mobile": "18000000218",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "c295d9ceb6f04802a65b057e6b55de4c",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm017",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968492
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm012",
                    "username": "itsm012",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm012@uyun.cn",
                    "mobile": "18000000213",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "d0ee22936bf94903967bea07d4bd92ad",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm012",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968244
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm003",
                    "username": "itsm003",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm003@uyun.cn",
                    "mobile": "18000000204",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "de096ffe8fc147feb7cca624a3a8ce3f",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157967000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm003",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157967930
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "admin",
                    "username": "admin",
                    "tenantName": null,
                    "contacts": null,
                    "email": "admin@uyun.cn",
                    "mobile": "15000000000",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "e10adc3949ba59abbe56e057f20f88dd",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502116967000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": "blue",
                    "root": true,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": null,
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": "0",
                    "expiryDate": null,
                    "passwordExpiryDate": null
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm006",
                    "username": "itsm006",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm006@uyun.cn",
                    "mobile": "18000000207",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "e638952a3ac046019106e1d6aa707cb5",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm006",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968056
                },
                {
                    "tenantId": "e10adc3949ba59abbe56e057f20f88dd",
                    "realname": "itsm014",
                    "username": "itsm014",
                    "tenantName": null,
                    "contacts": null,
                    "email": "itsm014@uyun.cn",
                    "mobile": "18000000215",
                    "passwd": null,
                    "industryId": null,
                    "companySizeId": null,
                    "userId": "f7fd935e77a246e1883b681b769722b0",
                    "userType": null,
                    "apiKeys": null,
                    "addTime": 1502157968000,
                    "office": null,
                    "removed": null,
                    "payType": null,
                    "language": null,
                    "timezone": null,
                    "timezoneId": null,
                    "timezoneName": null,
                    "description": null,
                    "inviteCode": null,
                    "qq": null,
                    "weixin": null,
                    "site": null,
                    "skin": null,
                    "root": false,
                    "status": null,
                    "products": null,
                    "userExcess": null,
                    "userNo": "itsm014",
                    "userCount": null,
                    "imagePath": "/tenant/userimages/default.jpg",
                    "astrictExpiry": null,
                    "expiryDate": null,
                    "passwordExpiryDate": 1502157968309
                }
            ],
            "ticketId": null
        },
        {
            "id": "00a53240c20d4ec4af045c1a768e422b",
            "name": "二线处理",
            "policy": 1,
            "users": null,
            "ticketId": null
        }
    ]
}
